version: '2'
services:
    web:
        build: 
          context: .
          dockerfile: ./Dockerfile.prod
        image: surfercrs4/openehrtoolprod
        network_mode: host
        env_file:
            - ./.env.prod