version: '3'
services:
    openehrtool:
        build: 
          context: .
          dockerfile: ./Dockerfile
        image: surfercrs4/openehrtool
        volumes:
            - .:/code
        network_mode: host
        env_file:
            - ./.env.dev
        depends_on:
            - "redis"        

    redis:
        image: redis:alpine
        ports:
        - 6379:6379
        command:  redis-server  /redis.conf
        volumes:
        - ./redis.conf:/redis.conf
