version: '2'
services:
    web:
        build: 
          context: .
          dockerfile: ./Dockerfile
        image: surfercrs4/openehrtool
        volumes:
            - .:/code
        network_mode: host
        env_file:
            - ./.env.dev
